repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
      - id: isort
        name: isort (python)
        args: [ "--diff" ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.7
    hooks:
      # Run the linter.
      - id: ruff-check
        args: ["--diff"]

  # 用 yapf 做格式化（支持自定义缩进）
  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
        args: ["--in-place"]

      - id: yapf
        name: yapf-diff          # 起个新名字，避免跟真正格式化冲突
        args: [ "--diff" ]
        verbose: true